// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var DiscordJs = require("discord.js");

((require('isomorphic-fetch')));

var token = "NTM3MDk1NzMxNTQzMjc3NTY4.Dzcrjw.VnyTD27MuFeQRI85dCKRrEHa4sc";

var botName = "ReasonBot";

var client = new DiscordJs.Client();

var login = client.login(token).then((function (info) {
          return Promise.resolve((console.log("Logged in as ReasonBot"), /* () */0));
        })).catch((function (err) {
        return Promise.resolve((console.log("Error: ", err), /* () */0));
      }));

client.on("ready", (function (param) {
        console.log("ready");
        return /* () */0;
      }));

exports.token = token;
exports.botName = botName;
exports.client = client;
exports.login = login;
/*  Not a pure module */
